# Generated by Django 3.2.3 on 2021-06-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
    ]
