# Generated by Django 3.2.3 on 2021-06-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_rename_question_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
