# Generated by Django 3.2.3 on 2021-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_auto_20210617_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='quoraTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='quora/topicImg')),
            ],
        ),
    ]
