# Generated by Django 3.2.3 on 2021-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0006_quoratopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoratopic',
            name='image',
            field=models.ImageField(upload_to='quora/topicImg/'),
        ),
    ]
