# Generated by Django 3.2.3 on 2021-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0007_alter_quoratopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='quora.quoraTopic'),
        ),
    ]
