# Generated by Django 3.2.3 on 2021-06-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_question_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topics',
            new_name='queTopics',
        ),
    ]
