# Generated by Django 3.2.3 on 2021-06-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0010_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
