# Generated by Django 3.2.3 on 2021-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0007_alter_quoratopic_image'),
        ('authentication', '0005_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(to='quora.quoraTopic'),
        ),
    ]
