# Generated by Django 3.2.3 on 2021-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='user.png', upload_to='auth/userImg/'),
        ),
    ]
